apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ng-pv-claim
  namespace: nginx-namespace
  labels:
    app: nginx-deployment
spec:
  resources:
    requests:
      storage: 2Gi
  accessModes:
    - ReadWriteMany