apiVersion: v1
kind: PersistentVolume
metadata:
  name: ng-pv
  namespace: nginx-namespace
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  nfs:
    path: /k8s/
    server: 192.168.2.65
    readOnly: false
