apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-service
  name: nginx-service
spec:
  ports:
  - name: nginx-service
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: nginx
