apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: wp-namespace
  name: mysql-pvc
  labels:
    app: wp-deployment
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi