apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: wp-namespace
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  #storageClassName: nfs-client
  persistentVolumeReclaimPolicy: Delete
  #hostPath:
  #  path: /k8s/wp-mysql
  nfs:
    path: /k8s/wp-mysql/
    server: 192.168.2.65
    readOnly: false