apiVersion: v1
kind: Service
metadata:
  name: wp-mysql
  namespace: wp-namespace
  labels:
    app: wordpress
spec:
  ports:
    - port: 3306
  selector:
    app: wordpress
    tier: mysql
  clusterIP: None