apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pvc
  namespace: wp-namespace
  labels:
    app: wp-deployment
spec:
  resources:
    requests:
      storage: 2Gi
  accessModes:
    - ReadWriteMany
