apiVersion: v1
kind: PersistentVolume
metadata:
  name: wp-pv
  namespace: wp-namespace
  labels:
    app: wordpress
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  nfs:
    path: /k8s/wp-deployment/
    server: 192.168.2.65