apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: wp-namespace
  labels:
    app: wordpress
spec:
  selector:
    app: wordpress
    tier: frontend
  ports:
  - name: http
    port: 80
  type: NodePort