apiVersion: v1
kind: PersistentVolume
metadata:
  name: docker-registry-pv
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  nfs:
    path: /var/nfs/general/docker-registry
    server: 192.168.10.61
  persistentVolumeReclaimPolicy: Retain